### ISSUE TITLE
Add priority packages

### ISSUE THREAD

**Issue by Ana06** [mandiant/VM-Packages#3]
Add the following priority packages:
- [X] cyberchef (cyberchef.vm - #15)
- [x] notepadplusplus (notepadplusplus.vm - #4)
- [X] pd64.exe (processdump.vm - #19)
- [x] wireshark (wireshark.vm - #12)
